[package]
name = "hexforge"
version = "0.1.0"
edition = "2024"
authors = ["xeran"]
description = "A simple http crafting and abuse tool for pentesting"
license = "MIT"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
